version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: books-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "123"
      MYSQL_DATABASE: "miniproject_db"
      TZ: "Asia/Jakarta"
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-p123"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

volumes:
  db_data:
